/*
 * Harness feature flag service client apis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = io.harness.ff_dotnet_client_sdk.openapi.Client.FileParameter;
using OpenAPIDateConverter = io.harness.ff_dotnet_client_sdk.openapi.Client.OpenAPIDateConverter;

namespace io.harness.ff_dotnet_client_sdk.openapi.Model
{
    /// <summary>
    /// AuthenticateProxyKeyRequest
    /// </summary>
    [DataContract(Name = "AuthenticateProxyKey_request")]
    internal partial class AuthenticateProxyKeyRequest : IEquatable<AuthenticateProxyKeyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticateProxyKeyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthenticateProxyKeyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticateProxyKeyRequest" /> class.
        /// </summary>
        /// <param name="proxyKey">proxyKey (required).</param>
        public AuthenticateProxyKeyRequest(string proxyKey = default(string))
        {
            // to ensure "proxyKey" is required (not null)
            if (proxyKey == null)
            {
                throw new ArgumentNullException("proxyKey is a required property for AuthenticateProxyKeyRequest and cannot be null");
            }
            this.ProxyKey = proxyKey;
        }

        /// <summary>
        /// Gets or Sets ProxyKey
        /// </summary>
        /// <example>896045f3-42ee-4e73-9154-086644768b96</example>
        [DataMember(Name = "proxyKey", IsRequired = true, EmitDefaultValue = true)]
        public string ProxyKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthenticateProxyKeyRequest {\n");
            sb.Append("  ProxyKey: ").Append(ProxyKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthenticateProxyKeyRequest);
        }

        /// <summary>
        /// Returns true if AuthenticateProxyKeyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthenticateProxyKeyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthenticateProxyKeyRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ProxyKey == input.ProxyKey ||
                    (this.ProxyKey != null &&
                    this.ProxyKey.Equals(input.ProxyKey))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProxyKey != null)
                {
                    hashCode = (hashCode * 59) + this.ProxyKey.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
