/*
 * Harness feature flag service client apis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = io.harness.ff_dotnet_client_sdk.openapi.Client.FileParameter;
using OpenAPIDateConverter = io.harness.ff_dotnet_client_sdk.openapi.Client.OpenAPIDateConverter;

namespace io.harness.ff_dotnet_client_sdk.openapi.Model
{
    /// <summary>
    /// Describes a distribution rule
    /// </summary>
    [DataContract(Name = "Distribution")]
    internal partial class Distribution : IEquatable<Distribution>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Distribution" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Distribution() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Distribution" /> class.
        /// </summary>
        /// <param name="bucketBy">The attribute to use when distributing targets across buckets (required).</param>
        /// <param name="variations">A list of variations and the weight that should be given to each (required).</param>
        public Distribution(string bucketBy = default(string), List<WeightedVariation> variations = default(List<WeightedVariation>))
        {
            // to ensure "bucketBy" is required (not null)
            if (bucketBy == null)
            {
                throw new ArgumentNullException("bucketBy is a required property for Distribution and cannot be null");
            }
            this.BucketBy = bucketBy;
            // to ensure "variations" is required (not null)
            if (variations == null)
            {
                throw new ArgumentNullException("variations is a required property for Distribution and cannot be null");
            }
            this.Variations = variations;
        }

        /// <summary>
        /// The attribute to use when distributing targets across buckets
        /// </summary>
        /// <value>The attribute to use when distributing targets across buckets</value>
        [DataMember(Name = "bucketBy", IsRequired = true, EmitDefaultValue = true)]
        public string BucketBy { get; set; }

        /// <summary>
        /// A list of variations and the weight that should be given to each
        /// </summary>
        /// <value>A list of variations and the weight that should be given to each</value>
        [DataMember(Name = "variations", IsRequired = true, EmitDefaultValue = true)]
        public List<WeightedVariation> Variations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Distribution {\n");
            sb.Append("  BucketBy: ").Append(BucketBy).Append("\n");
            sb.Append("  Variations: ").Append(Variations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Distribution);
        }

        /// <summary>
        /// Returns true if Distribution instances are equal
        /// </summary>
        /// <param name="input">Instance of Distribution to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Distribution input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BucketBy == input.BucketBy ||
                    (this.BucketBy != null &&
                    this.BucketBy.Equals(input.BucketBy))
                ) && 
                (
                    this.Variations == input.Variations ||
                    this.Variations != null &&
                    input.Variations != null &&
                    this.Variations.SequenceEqual(input.Variations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BucketBy != null)
                {
                    hashCode = (hashCode * 59) + this.BucketBy.GetHashCode();
                }
                if (this.Variations != null)
                {
                    hashCode = (hashCode * 59) + this.Variations.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
