/*
 * Harness feature flag service client apis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = io.harness.ff_dotnet_client_sdk.openapi.Client.FileParameter;
using OpenAPIDateConverter = io.harness.ff_dotnet_client_sdk.openapi.Client.OpenAPIDateConverter;

namespace io.harness.ff_dotnet_client_sdk.openapi.Model
{
    /// <summary>
    /// The state of a flag either off or on
    /// </summary>
    /// <value>The state of a flag either off or on</value>
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum FeatureState
    {
        /// <summary>
        /// Enum On for value: on
        /// </summary>
        [EnumMember(Value = "on")]
        On = 1,

        /// <summary>
        /// Enum Off for value: off
        /// </summary>
        [EnumMember(Value = "off")]
        Off = 2
    }

}
