/*
 * Harness feature flag service client apis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = io.harness.ff_dotnet_client_sdk.openapi.Client.FileParameter;
using OpenAPIDateConverter = io.harness.ff_dotnet_client_sdk.openapi.Client.OpenAPIDateConverter;

namespace io.harness.ff_dotnet_client_sdk.openapi.Model
{
    /// <summary>
    /// A variation and the weighting it should receive as part of a percentage rollout
    /// </summary>
    [DataContract(Name = "WeightedVariation")]
    internal partial class WeightedVariation : IEquatable<WeightedVariation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WeightedVariation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WeightedVariation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WeightedVariation" /> class.
        /// </summary>
        /// <param name="variation">The variation identifier (required).</param>
        /// <param name="weight">The weight to be given to the variation in percent (required).</param>
        public WeightedVariation(string variation = default(string), int weight = default(int))
        {
            // to ensure "variation" is required (not null)
            if (variation == null)
            {
                throw new ArgumentNullException("variation is a required property for WeightedVariation and cannot be null");
            }
            this.Variation = variation;
            this.Weight = weight;
        }

        /// <summary>
        /// The variation identifier
        /// </summary>
        /// <value>The variation identifier</value>
        /// <example>off-variation</example>
        [DataMember(Name = "variation", IsRequired = true, EmitDefaultValue = true)]
        public string Variation { get; set; }

        /// <summary>
        /// The weight to be given to the variation in percent
        /// </summary>
        /// <value>The weight to be given to the variation in percent</value>
        /// <example>50</example>
        [DataMember(Name = "weight", IsRequired = true, EmitDefaultValue = true)]
        public int Weight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WeightedVariation {\n");
            sb.Append("  Variation: ").Append(Variation).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WeightedVariation);
        }

        /// <summary>
        /// Returns true if WeightedVariation instances are equal
        /// </summary>
        /// <param name="input">Instance of WeightedVariation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WeightedVariation input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Variation == input.Variation ||
                    (this.Variation != null &&
                    this.Variation.Equals(input.Variation))
                ) && 
                (
                    this.Weight == input.Weight ||
                    this.Weight.Equals(input.Weight)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Variation != null)
                {
                    hashCode = (hashCode * 59) + this.Variation.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Weight.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
