/*
 * Harness feature flag service client apis
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cf@harness.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using io.harness.ff_dotnet_client_sdk.openapi.Client;
using io.harness.ff_dotnet_client_sdk.openapi.Model;

namespace io.harness.ff_dotnet_client_sdk.openapi.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IMetricsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Send metrics to the Analytics server.
        /// </summary>
        /// <remarks>
        /// Send metrics to Analytics server
        /// </remarks>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <returns></returns>
        void PostMetrics(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics));

        /// <summary>
        /// Send metrics to the Analytics server.
        /// </summary>
        /// <remarks>
        /// Send metrics to Analytics server
        /// </remarks>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PostMetricsWithHttpInfo(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IMetricsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Send metrics to the Analytics server.
        /// </summary>
        /// <remarks>
        /// Send metrics to Analytics server
        /// </remarks>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PostMetricsAsync(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Send metrics to the Analytics server.
        /// </summary>
        /// <remarks>
        /// Send metrics to Analytics server
        /// </remarks>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PostMetricsWithHttpInfoAsync(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IMetricsApi : IMetricsApiSync, IMetricsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal partial class MetricsApi : IDisposable, IMetricsApi
    {
        private io.harness.ff_dotnet_client_sdk.openapi.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public MetricsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public MetricsApi(string basePath)
        {
            this.Configuration = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.MergeConfigurations(
                io.harness.ff_dotnet_client_sdk.openapi.Client.GlobalConfiguration.Instance,
                new io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new io.harness.ff_dotnet_client_sdk.openapi.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public MetricsApi(io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.MergeConfigurations(
                io.harness.ff_dotnet_client_sdk.openapi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new io.harness.ff_dotnet_client_sdk.openapi.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MetricsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MetricsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.MergeConfigurations(
                io.harness.ff_dotnet_client_sdk.openapi.Client.GlobalConfiguration.Instance,
                new io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new io.harness.ff_dotnet_client_sdk.openapi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public MetricsApi(HttpClient client, io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.MergeConfigurations(
                io.harness.ff_dotnet_client_sdk.openapi.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new io.harness.ff_dotnet_client_sdk.openapi.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MetricsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public MetricsApi(io.harness.ff_dotnet_client_sdk.openapi.Client.ISynchronousClient client, io.harness.ff_dotnet_client_sdk.openapi.Client.IAsynchronousClient asyncClient, io.harness.ff_dotnet_client_sdk.openapi.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = io.harness.ff_dotnet_client_sdk.openapi.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public io.harness.ff_dotnet_client_sdk.openapi.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public io.harness.ff_dotnet_client_sdk.openapi.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public io.harness.ff_dotnet_client_sdk.openapi.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public io.harness.ff_dotnet_client_sdk.openapi.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public io.harness.ff_dotnet_client_sdk.openapi.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Send metrics to the Analytics server. Send metrics to Analytics server
        /// </summary>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <returns></returns>
        public void PostMetrics(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics))
        {
            PostMetricsWithHttpInfo(environmentUUID, cluster, metrics);
        }

        /// <summary>
        /// Send metrics to the Analytics server. Send metrics to Analytics server
        /// </summary>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public io.harness.ff_dotnet_client_sdk.openapi.Client.ApiResponse<Object> PostMetricsWithHttpInfo(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics))
        {
            // verify the required parameter 'environmentUUID' is set
            if (environmentUUID == null)
                throw new io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException(400, "Missing required parameter 'environmentUUID' when calling MetricsApi->PostMetrics");

            io.harness.ff_dotnet_client_sdk.openapi.Client.RequestOptions localVarRequestOptions = new io.harness.ff_dotnet_client_sdk.openapi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("environmentUUID", io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.ParameterToString(environmentUUID)); // path parameter
            if (cluster != null)
            {
                localVarRequestOptions.QueryParameters.Add(io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.ParameterToMultiMap("", "cluster", cluster));
            }
            localVarRequestOptions.Data = metrics;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api-key", this.Configuration.GetApiKeyWithPrefix("api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/metrics/{environmentUUID}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostMetrics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send metrics to the Analytics server. Send metrics to Analytics server
        /// </summary>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PostMetricsAsync(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await PostMetricsWithHttpInfoAsync(environmentUUID, cluster, metrics, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Send metrics to the Analytics server. Send metrics to Analytics server
        /// </summary>
        /// <exception cref="io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environmentUUID">environment parameter in query.</param>
        /// <param name="cluster">Unique identifier for the cluster for the account (optional)</param>
        /// <param name="metrics"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<io.harness.ff_dotnet_client_sdk.openapi.Client.ApiResponse<Object>> PostMetricsWithHttpInfoAsync(string environmentUUID, string cluster = default(string), Metrics metrics = default(Metrics), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'environmentUUID' is set
            if (environmentUUID == null)
                throw new io.harness.ff_dotnet_client_sdk.openapi.Client.ApiException(400, "Missing required parameter 'environmentUUID' when calling MetricsApi->PostMetrics");


            io.harness.ff_dotnet_client_sdk.openapi.Client.RequestOptions localVarRequestOptions = new io.harness.ff_dotnet_client_sdk.openapi.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("environmentUUID", io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.ParameterToString(environmentUUID)); // path parameter
            if (cluster != null)
            {
                localVarRequestOptions.QueryParameters.Add(io.harness.ff_dotnet_client_sdk.openapi.Client.ClientUtils.ParameterToMultiMap("", "cluster", cluster));
            }
            localVarRequestOptions.Data = metrics;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("api-key", this.Configuration.GetApiKeyWithPrefix("api-key"));
            }
            // authentication (BearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/metrics/{environmentUUID}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostMetrics", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
